### PR TITLE
Portfolio: details popup window

### PR DESCRIPTION
**Pull request by jecode93**
### For this milestone of my portfolio website we:

* Implement the following interactions:
    * When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
    * When the user clicks (or taps) the close (X) button, the popup disappears.

* In order to associate each project with the popup window details, we refactor the project section:
    * We use a JavaScript array to store all of the information for all projects.
    * For each project we store pieces of data in a JavaScript object.
    * We update the main page so that the projects section is created dynamically using the information stored in that JavaScript object.
    * After that, we implement the popup window.

### CODE REVIEW

**Review by Eternalgratis — CHANGES_REQUESTED** [review]
# Status: Required Changes ♻️
## Hi @jecode93 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
almost-there

## Highlights
✅ You used the correct GitHub flow
✅ Descriptive pull request message
✅ Documented your work professionally

## Required Changes ♻️
_Check the comments under the review._
- Kudos on implementing some of the project requirements so far🖐however, there are still some adjustments to be made. Currently, your popup isn't showing the details of each project card whenever it is been clicked. Kindly make some adjustments to your styling to implement these changes. Please check the image attached below for comparison and better understanding.

Figma design
image


Your design
image



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Cabraham1 — COMMENTED** [review]
# INVALID ❌ 

Hi @jecode93 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 😓

## Invalid Code Review Request ❌

- [ ] Unfortunately, you have submitted a project that has Eslint linters error, I kindly suggest you fix the error

_**Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready**_ 🤝🙏

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jecode93** [comment]
@Cabraham1 Hoo man,

You can't do this, the errors are not from me, the other CR saw that and doesn't say comment about that and you tell me to fix them!

You stress me a lot with this comment.

**Review by shahadat3669 — CHANGES_REQUESTED** [review]
Hi @jecode93 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

- [ ] Unfortunately, you have submitted a project that has Eslint linters error, I kindly suggest you fix the error

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jecode93** [comment]
@shahadat3669 Hello...

Please tell me how I will be able to fix an error that is from linters itself while on slack they said to not worry about that?

**Review by shahadat3669 — CHANGES_REQUESTED** [review]
Hi Everyone, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✅ Good PR Title
✅ Good PR Description
✅ Good Readme File

 ## Required Changes ♻️

- [ ] As the previous reviewer requested, You improved the UI of the project however, there are still some adjustments to be made. Currently, your popup does not align with the design. 🙏 Kindly make some adjustments to your styling to implement these changes. Please check the image attached below for comparison and better understanding.

- [ ] For the desktop version:

| Your | Design |
| --- | --- |
| image | Template 1- Detail|

- [ ] For the mobile version:

| Your | Design |
| --- | --- |
| image | Template 1-Mobile-Detail |
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can consider bellow suggestion in your next project:

- [ ] [Optional] You have submitted a project that does not follow the [GitHub Flows](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md). According to GitHub Flows, the base branch name should be "main." However, in your project, the base branch name is currently "main." Please rename or change your base branch name to "main" to align with the recommended practice. You can refer to this [official document](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) for further assistance on renaming a branch. Keep up the good work! 👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Alusp — CHANGES_REQUESTED** [review]
Hi @jecode93 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

close


 ## Highlights
- [ ] Good Commit History :green_circle: 
- [ ] Good Github Flow :green_circle: 
- [ ] Good PR Summary :green_circle: 
 

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Good job implementing the changes, :clap: As the previous reviewer requested, You improved the UI of the project however, there are still some adjustments to be made. Currently, your popup does not align with the design.  Kindly make some adjustments to your styling to implement these changes. Please check the image attached below for comparison and better understanding. :slightly_smiling_face:  

Below is an illustration of the difference: :arrow_down: 

<table>
    <tr>
      <td>Your Design</td>
      <td>Figma Design</td>
    </tr>
    <tr>
      <td>

UserMobilePopup

</td>
      <td>

Figma Popup Design

</td>
    </tr>
  </table> 


<table>
    <tr>
      <td>Your Design</td>
      <td>Figma Design</td>
    </tr>
    <tr>
      <td>

UserDesktopPopup

</td>
      <td>

Desktop Figma Desin Popup

</td>
    </tr>
  </table> 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jecode93** [comment]
@Alusp sorry but I think the problem is from your screen.

Here is the design from my screen
Screen Shot 2023-06-22 at 11 58 53 AM
Screen Shot 2023-06-22 at 11 59 58 AM


I don't think the problem is with me...

**Comment by jecode93** [comment]
@Alusp After all of this work did you want to stress me with this kind of problem from your screen?

**Comment by Alusp** [comment]
Hello @jecode93, I know you are doing a very good job, however its still does not conform to the figma design, I have just tested it on another screen. and Please make sure you check your browser zoom measurement to be 100%. following a design guide promotes consistency, efficiency, user experience, branding, collaboration, scalability, and accessibility. It helps create a cohesive and well-executed project while reducing design-related challenges and enhancing the overall quality of the end product. :slightly_smiling_face:

**Review by Cabraham1 — CHANGES_REQUESTED** [review]
# Required Changes :recycle:
almost-there

## Hey @jecode93   :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title

✔️ Following some requirements

- [ ] Great work on incorporating the modifications, 👏 as per the suggestions of the previous code reviewer. You have enhanced the project's user interface, but there are still a few tweaks required. At the moment, the popup you've implemented doesn't really match the overall design for the desktop view.
  
- [ ] To fix the design error I kindly suggest you 
- reduce the size of the popup images
- reduce the popup container to accommodate all its children's content
- [ ] Your current design 
image


# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jecode93** [comment]
@Cabraham1 I made all the changes as requested but it is always good on my computer but not yours, I see other's work that is uglies than mine that was approved but it appears you want me to fail this week.

Here is my image
Screen Shot 2023-06-22 at 2 05 28 PM

I really don't know what to do next. 🤦🏽‍♂️🤦🏽‍♂️🤦🏽‍♂️

**Comment by jecode93** [comment]
I already request extra reviews for this project. But it's volunteer how you keep this discussion to disapprove my project as you know there is a limit for the reviews.

**Review by Cabraham1 — APPROVED** [review]
Hi @jecode93  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by nicupop729 — COMMENTED** [review]
Hello @jecode93 👋,

_This is an additional review as a result of the second opinion request._

Well done on the remarkable effort put into this milestone!

Please be aware that after requesting a Second Opinion review following a review you disagree with, it is not recommended to make additional commits or request another review through the dashboard.

Since this CRR has been approved, the Second Opinion review is now redundant.

Keep rocking 🚀!

**Pull request merged**
